AllCops:
  Excludes:
    - .bundle/**
    - .git/**
    - .vvm_cache/**
    - coverage/**
    - etc/**
    - pkg/**
    - vendor/**
LineLength:
  Max: 80
MethodLength:
  Max: 30
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
AccessorMethodName:
  Enabled: false
