AllCops:
  Exclude:
    - .bundle/**/*
    - .git/**/*
    - .vvm_cache/**/*
    - coverage/**/*
    - etc/**/*
    - pkg/**/*
    - vendor/**/*
    - Rakefile
    - vvm-rb.gemspec
LineLength:
  Max: 90
Documentation:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
AssignmentInCondition:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
