AllCops:
  Exclude:
    - .bundle/**/*
    - .git/**/*
    - .vvm_cache/**/*
    - coverage/**/*
    - etc/**/*
    - pkg/**/*
    - vendor/**/*
    - Rakefile
    - vvm-rb.gemspec
LineLength:
  Max: 80
MethodLength:
  Max: 30
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
SpecialGlobalVars:
  Enabled: false
AccessorMethodName:
  Enabled: false
PredicateName:
  Enabled: false
FileName:
  Enabled: false
