language: ruby
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
env:
  global:
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH:~/.rvm/rubies/ruby-2.2.0/lib:~/.rvm/rubies/ruby-2.3.0/lib:~/.rvm/rubies/ruby-2.4.0/lib"
notifications:
  email: false
