#!/bin/bash

__vvm_rb_configure_path()
{
  local vvm_rb_bin_path="$HOME/.vvm-rb/vims/current/bin"

  echo "$PATH" | grep -Fqv "$vvm_rb_bin_path" &&
    PATH="$vvm_rb_bin_path:$PATH"
}


__vvm_rb_configure_path

# __END__
